version: '3.8'

services:

  web:

    build: ./compose-task

    ports:

      - "5000:5000"

    depends_on:

      - database
    environment:
      - DATABASE_URL=postgresql://db_admin:112233@database:5432/mydb


  database:

    image: postgres:15

    restart: always

    environment:

      POSTGRES_USER: db_admin

      POSTGRES_PASSWORD: 112233

      POSTGRES_DB: mydb

    volumes:
     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
